# Generated by Django 3.1.7 on 2021-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField(default=-1)),
                ('order', models.IntegerField(default=0)),
                ('x_position', models.IntegerField(default=0)),
                ('y_position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='press',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField(default=-1)),
                ('order', models.IntegerField(default=0)),
                ('button', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='scroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField(default=-1)),
                ('order', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='write',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField(default=-1)),
                ('order', models.IntegerField(default=0)),
                ('string', models.CharField(max_length=1000)),
            ],
        ),
    ]
