# Generated by Django 3.1.7 on 2021-05-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='loop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField(default=-1)),
                ('order_start', models.IntegerField(default=0)),
                ('order_end', models.IntegerField(default=0)),
                ('iterations', models.IntegerField(default=0)),
            ],
        ),
    ]
