# Generated by Django 3.1.7 on 2021-05-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_wait'),
    ]

    operations = [
        migrations.AddField(
            model_name='wait',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
