# Generated by Django 3.1.7 on 2021-05-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_wait_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='description',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
