# Generated by Django 3.1.7 on 2021-05-31 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_bot_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
