# Generated by Django 3.1.7 on 2021-05-31 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210531_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
