# Generated by Django 3.1.7 on 2021-05-31 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210531_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
