# Generated by Django 3.1.7 on 2021-06-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210531_0447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bot',
        ),
    ]
