# Generated by Django 3.1.7 on 2021-06-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='valid_image',
            field=models.BooleanField(default=False),
        ),
    ]
