# Generated by Django 3.1.7 on 2021-06-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='failsafe',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
