# Generated by Django 3.1.7 on 2021-06-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_bot_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='drag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.IntegerField(default=-1)),
                ('order', models.IntegerField(default=0)),
                ('startx', models.IntegerField(default=0)),
                ('starty', models.IntegerField(default=0)),
                ('endx', models.IntegerField(default=0)),
                ('endy', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=-1)),
                ('hold', models.BooleanField(default=False)),
            ],
        ),
    ]
